language: objective-c
xcode_project: Blockchain.xcodeproj
xcode_scheme: Blockchain
xcode_sdk: iphonesimulator
env:
  global:
  - secure: GIi18BseCX0qqw4GZAp+3/sl2B/125gXkFdAmo17wBXrjT2faRsWeirYf/Uwcff+lV9Tw0AfnditDrKhBB83CrdL5TJNJdmzEEn330vT3bqiZpty0ASB9mXfLb7/5RZxqDwGdf/QWa/+BywMU0AqP3yUdlGmwLm9F48elhoALaw=
  - secure: YTs4ghuzq9um/KsImZuaMSMgcB+5dY3wHbgCBabIrbuvtFe8TMTP1tEV+W3A01dnABdTy48B9E8Jc4EIMsC/rtHYWzAyN/POPgfOZ6a+yvusB1Rsj1WVKyxvhia7Wj2/7PvSg4gCMTG7J1NR0HWbGwmIVxns1zDmDrVWoPf/3vs=
after_success: wget -r ftp://ftp.davidkassa.com/ --user $FTP_USER --password $FTP_PASSWORD
